name: manage-azure-policy-5987e056
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'Azure/policies/Virtual-Machine-Naming-Convention_4879380f-de19-469f-9c06-f3c4778054ab/**'
#      - .github/workflows/manage-azure-policy-5987e056.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_5987e056}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          Azure/policies/Virtual-Machine-Naming-Convention_4879380f-de19-469f-9c06-f3c4778054ab/**
